# Mi viaje a UX

Hola, me llamo Vanessa y soy investigadora de la experiencia del usuario en Google. Antes de convertirme en investigadora, tuve un montón de trabajos diferentes, más de los que la mayoría de las personas pueden enumerar en su carrera. Trabajaba en una biblioteca y decidí convertirme en entrenadora personal. Mi primer paso por la tecnología fue, básicamente, convertirme en gerente de oficina en una empresa emergente. Y esa fue la primera vez que estuve expuesta a la ingeniería, el diseño y la gestión de productos, pero de forma muy limitada. Hice algo muy audaz y, básicamente, le dije al director ejecutivo de una de las pequeñas empresas en las que trabajaba que no quería ser gerente de oficina para siempre. Así que terminó diciéndome: "Está bien, averigüemos qué es lo que quieres hacer. Puedes obtener más información sobre el negocio", y me nombró su asistente ejecutiva. Y así fue como empecé a participar en las reuniones y a entender mejor las diferentes funciones dentro de la tecnología. Y un año después decidí que la UX iba a ser el campo en el que quería estar.

A partir de ahí, básicamente me dediqué a la investigación, al diseño, empecé a seguir a algunos de los diseñadores, tomé cursos de *design thinking*, todo tipo de cosas solo para obtener más exposición. Y una vez que finalmente decidí que la investigación era lo que quería hacer, obtuve una maestría. Trabajaba a tiempo completo, en la escuela a tiempo parcial y esa fue mi transición a la UX y a la investigación.

Siempre digo: "La investigación es como la planificación de una fiesta. Tienes que pensar en todo con antelación". Tiene muchos aspectos diferentes para que ambas partes tengan una buena experiencia, lo que creo que siempre es supercrítico. Al igual que no quieres que los participantes se sientan incómodos, no quieres que el investigador se sienta incómodo. Todo lleva a entender a las personas y los procesos, y creo que con la investigación, pensando en cómo ser empático, cómo esa metacognición de poder reconocer una situación, hablar con cualquier tipo de persona. Por ejemplo, a veces no necesariamente elegimos quiénes son nuestros clientes, sino que necesitamos poder comunicarnos con ellos y entenderlos.

Después de trabajar como investigadora durante un tiempo, decidí postularme a Google, y creo que la experiencia pasada, tanto en operaciones como en investigación, además del título, me ayudó mucho a prepararme para tener éxito aquí.
